import '@/assets/styles/app.scss';
import TheFooter from '@/components/TheFooter';
import TheHeader from '@/components/TheHeader';
import type { Metadata } from 'next';
import { UIProviders } from './ui-providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <UIProviders>
          <TheHeader />
          {children}
          <TheFooter />
        </UIProviders>
      </body>
    </html>
  );
}
